app/models/test_question.py
from app.extensions import db

class TestQuestion(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    test_id = db.Column(db.Integer, db.ForeignKey('test.id'))
    question_text = db.Column(db.Text, nullable=False)

    test = db.relationship("Test", back_populates="questions")
    answer_options = db.relationship("AnswerOption", back_populates="question", cascade="all, delete-orphan")

app/forms/test_question_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, FieldList, FormField, IntegerField, SubmitField, TextAreaField, BooleanField
from wtforms.validators import DataRequired

class AnswerOptionForm(FlaskForm):
    option_text = StringField('Option Text', validators=[DataRequired()])
    is_correct = BooleanField('Is Correct?')

class TestQuestionForm(FlaskForm):
    question_text = TextAreaField('Question Text', validators=[DataRequired()])
    answer_options = FieldList(FormField(AnswerOptionForm), min_entries=4, max_entries=4)
    
    submit = SubmitField('Submit Test question and Answers')

app/views/test_question.py
from flask import Blueprint, flash, request, redirect, render_template, url_for
from flask_login import login_required, current_user
from app.utils.decorators import admin_required
from app.services.test_question_service import TestQuestionService
from app.services.answer_option_service import AnswerOptionService
from app.forms.test_question_form import TestQuestionForm


bp = Blueprint('test_question', __name__)

@bp.route('/detail/<int:test_question_id>')
def detail(test_question_id):
    """Display test question details"""
    test_question = TestQuestionService.get_test_question_by_id(test_question_id)
    
    if not test_question:
        flash('Test has no questions.', 'error')
        return redirect(url_for('test.index'))
    
    return render_template('test_question/test_question_detail.html',
                           title='Test Question Detail',
                           question=test_question)

@bp.route('/add_question/<int:test_id>', methods=['GET', 'POST'])
def add_question(test_id):
    form = TestQuestionForm()

    if form.validate_on_submit():

        question_text = form.question_text.data
        test_question = TestQuestionService.create_and_flush_question(test_id, question_text)


        for answer_form in form.answer_options.entries:
            option_text = answer_form.option_text.data
            is_correct = answer_form.is_correct.data
            AnswerOptionService.create_answer_for_test_question_id(test_question_id=test_question.id,
                                                                                   option_text=option_text,
                                                                                   is_correct=is_correct)

        TestQuestionService.commit_changes()
        flash('Question and answers added successfully!', 'success')
        return redirect(url_for('test.detail', test_id=test_id))
    
    return render_template('test_question/add_question.html', form=form, test_id=test_id)


@bp.route('/edit_question/<int:test_question_id>', methods=['GET', 'POST'])
def edit_question(test_question_id):
    question = TestQuestionService.get_test_question_by_id(test_question_id)
    form = TestQuestionForm(obj=question)

    if form.validate_on_submit():
        try:
            TestQuestionService.update_test_question_from_form(question, form)
            flash('Question updated successfully!')
            return redirect(url_for('test_question.detail', test_question_id=test_question_id))
        except ValueError as e:
            flash(str(e), 'danger')

    return render_template('test_question/edit_question.html', form=form, question=question, test_question_id=test_question_id)

app/templates/test_question/add_question.html
{% extends "dashboard_base.html" %}
{% block title %}Add Question and its answer options {% endblock %}
{% block dashboard_content %}
<form
  method="POST"
  action="{{ url_for('test_question.add_question', test_id=test_id) }}">
    {{ form.hidden_tag() }}
    <p>
        {{ form.question_text.label }}<br>
        {{ form.question_text }}
    </p>

    <h4>Answer Options</h4>
    {% for option_form in form.answer_options %}
      {{ option_form.option_text.label }} {{ option_form.option_text }}
      {{ option_form.is_correct.label }} {{ option_form.is_correct }}
      <br>
    {% endfor %}

    <p>{{ form.submit }}</p>
</form>
{% endblock %}

app/templates/test_question/edit_question.html
{% extends "dashboard_base.html" %}
{%block page_title%}Edit Question and it's answer options {%endblock%}
{% block dashboard_content %}
<form
  method="POST"
  action="{{ url_for('test_question.edit_question', test_question_id=test_question_id) }}">
    {{ form.hidden_tag() }}
    <p>
        {{ form.question_text.label }}<br>
        {{ form.question_text }}
    </p>

    <h4>Answer Options</h4>
    {% for option_form in form.answer_options %}
      {{ option_form.option_text.label }} {{ option_form.option_text }}
      {{ option_form.is_correct.label }} {{ option_form.is_correct }}
      <br>
    {% endfor %}

    <p>{{ form.submit }}</p>
</form>
{% endblock %}

app/templates/test_question/test_question_detail.html
{% extends "dashboard_base.html" %} {% block title %}Test Question Details{% endblock %} {% block
dashboard_content %}
<div class="container fade-in">
  <h1>{{ question }}</h1>

  <div class="feature-card">
    <h3>Question belong to Test:</h3>
    <a href="{{ url_for('test.detail', test_id=question.test.id)}}">
      <p>{{ question.test.name }}</p></a>
  </div>

  <div class="feature-card">
    <h3>Question and answer Options:</h3>
    {{ question.question_text }}
    {% if question.answer_options %}
    <ul>
      {% for answer in question.answer_options %}
        {% if answer.is_correct == 1 %}
          <li><strong>{{ answer.option_text }}</strong></li>
        {% else %}
          <li>{{ answer.option_text }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  {% else %}
    <p>Test has no answer options added.</p>
  {% endif %}
</div>
    <a href="{{ url_for('test_question.edit_question', test_question_id=question.id )}}">
        Edit Question
    </a>
</div>
{% endblock %}